@host = http://localhost:8080
@contentType = application/json

### [사전작업] 로그인 및 토큰 저장
POST {{host}}/api/v1/auth/login
Content-Type: {{contentType}}

{
  "username": "testuser",
  "password": "password123!"
}

> {%
  client.global.set("accessToken", response.body["data"]["accessToken"]);
  client.global.set("refreshToken", response.body["data"]["refreshToken"]);
%}

### 게시글 작성
POST {{host}}/api/v1/posts
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "content": "테스트 내용입니다."
}

> {%
  client.global.set("postId", response.body["data"]["postId"]);
%}

### 게시글 조회
GET {{host}}/api/v1/posts/{{postId}}

### 게시글 수정
PUT {{host}}/api/v1/posts/{{postId}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "content": "수정된 내용"
}

### 게시글 삭제
DELETE {{host}}/api/v1/posts/{{postId}}
Authorization: Bearer {{accessToken}}