name: OpenAPI Docs

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - 'api/**'
      - '.github/workflows/openapi.yaml'


jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Generate OpenAPI Docs
        run: |
          chmod +x gradlew
          ./gradlew generateOpenApiDocs

      - name: Upload OpenAPI Spec
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: build/openapi.json

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'OpenAPI documentation has been generated. You can check it in the Artifacts section.'
            })
